#ifndef TAIR_LOG_HPP
#define TAIR_LOG_HPP

#define log_info(fmt,...) fprintf(stdout, fmt"\n",##__VA_ARGS__)
#define log_error(fmt,...) fprintf(stdout, fmt"\n",##__VA_ARGS__)
#define log_warn(fmt,...) fprintf(stdout, fmt"\n",##__VA_ARGS__)
#define log_debug(fmt,...) fprintf(stdout, fmt"\n",##__VA_ARGS__)

#define EXIT_SUCCESS 0
enum {
    TAIR_RETURN_SUCCESS = 0,
    TAIR_DUP_WAIT_RSP = 133,
    TAIR_HAS_MORE_DATA = 150,

    TAIR_RETURN_NOT_INIT = -4002,
    TAIR_RETURN_NOT_SUPPORTED = -4001,
    TAIR_RETURN_PROXYED = -4000,
    TAIR_RETURN_FAILED = -3999,
    TAIR_RETURN_DATA_NOT_EXIST = -3998,
    TAIR_RETURN_VERSION_ERROR = -3997,
    TAIR_RETURN_TYPE_NOT_MATCH = -3996,

    TAIR_RETURN_PLUGIN_ERROR = -3995,
    TAIR_RETURN_SERIALIZE_ERROR = -3994,
    TAIR_RETURN_ITEM_EMPTY = -3993,
    TAIR_RETURN_OUT_OF_RANGE = -3992,
    TAIR_RETURN_ITEMSIZE_ERROR = -3991,

    TAIR_RETURN_SEND_FAILED = -3990,
    TAIR_RETURN_TIMEOUT = -3989,
    TAIR_RETURN_SERVER_CAN_NOT_WORK = -3987,
    TAIR_RETURN_WRITE_NOT_ON_MASTER = -3986,

    TAIR_RETURN_DUPLICATE_BUSY = -3985,
    TAIR_RETURN_MIGRATE_BUSY = -3984,

    TAIR_RETURN_PARTIAL_SUCCESS = -3983,
    TAIR_RETURN_INVALID_ARGUMENT = -3982,
    TAIR_RETURN_CANNOT_OVERRIDE = -3981,

    TAIR_RETURN_DEC_BOUNDS = -3980,
    TAIR_RETURN_DEC_ZERO = -3979,
    TAIR_RETURN_DEC_NOTFOUND = -3978,

    TAIR_RETURN_PROXYED_ERROR = -3977,

    TAIR_RETURN_FLOW_CONTROL = -3971,
    TAIR_RETURN_INVAL_CONN_ERROR = -3970,
    TAIR_RETURN_HIDDEN = -3969,
    TAIR_RETURN_QUEUE_OVERFLOWED = -3968,
    TAIR_RETURN_SHOULD_PROXY = -3967,

    // for lock
            TAIR_RETURN_LOCK_EXIST = -3975,
    TAIR_RETURN_LOCK_NOT_EXIST = -3974,

    // remove/update and mtime_care but mtime is early
            TAIR_RETURN_MTIME_EARLY = -3976,

    TAIR_RETURN_REMOVE_NOT_ON_MASTER = -4101,
    TAIR_RETURN_REMOVE_ONE_FAILED = -4102,

    TAIR_RETURN_OP_INVALID_PARAM = -4201,
    TAIR_RETURN_OP_GROUP_NOT_FOUND = -4202,
    TAIR_RETURN_NO_MORE_AREA = -4203,
    TAIR_RETURN_AREA_EXISTED = -4204,
    TAIR_RETURN_AREA_NOT_EXISTED = -4205,
    TAIR_RETURN_NOT_PERMITTED = -4206,
    TAIR_RETURN_REFUSED = -4207,

    TAIR_RETURN_DUPLICATE_IDMIXED = -5001,
    TAIR_RETURN_DUPLICATE_DELAY = -5002,
    TAIR_RETURN_DUPLICATE_REACK = -5003,
    TAIR_RETURN_DUPLICATE_ACK_WAIT = -5004,
    TAIR_RETURN_DUPLICATE_ACK_TIMEOUT = -5005,
    TAIR_RETURN_DUPLICATE_SEND_ERROR = -5006,

    TAIR_RETURN_REMOTE_NOTINITED = -5106,
    TAIR_RETURN_REMOTE_SLOW = -5107,
    TAIR_RETURN_REMOTE_NOTINIT = -5108,
    TAIR_RETURN_REMOTE_DISKSAVE_FAILED = -5109,
    TAIR_RETURN_REMOTE_MISS = -5110,
    TAIR_RETURN_REMOTE_RSP_FAILED = -5111,
    TAIR_RETURN_REMOTE_NOLOCAL = -5112,
    //cann't find the dataserver.
            TAIR_RETURN_NONE_DATASERVER = -5113,
    //for bounded counter.
            TAIR_RETURN_COUNTER_OUT_OF_RANGE = -5114,
    TAIR_RETURN_PAUSED = -5116, // just use inside of dataserver
    TAIR_RETURN_READ_ONLY = -5117,

    TAIR_RETURN_KEY_EXISTS = -5200,
};

enum {
    TAIR_SERVERFLAG_CLIENT = 0,
    TAIR_SERVERFLAG_DUPLICATE,   // 1
    TAIR_SERVERFLAG_MIGRATE,     // 2
    TAIR_SERVERFLAG_PROXY,       // 3
    TAIR_SERVERFLAG_RSYNC,       // 4
    // rsynced proxy request should not be rsynced again,
    // this flag is useless when do proxy logic is eliminated.
            TAIR_SERVERFLAG_RSYNC_PROXY, // 5
};

enum {
    TAIR_ADMIN_CONFIG_FLAG_NAMESPACE = 1,
    TAIR_ADMIN_CONFIG_FLAG_FLOWCONTROL,
};
#endif
